// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKV3U6NgPSuTCagYbOqqDK1NFkWoDMpjw',
    appId: '1:597094987517:web:f522e91c8720cabbd0f094',
    messagingSenderId: '597094987517',
    projectId: 'push-notification-1ecd2',
    authDomain: 'push-notification-1ecd2.firebaseapp.com',
    storageBucket: 'push-notification-1ecd2.firebasestorage.app',
    measurementId: 'G-0D1ZQJGF7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVuVZHU7rZ_ROP7dQNwCQfIeGMtRv9V2U',
    appId: '1:597094987517:android:33d8f4eb7df221edd0f094',
    messagingSenderId: '597094987517',
    projectId: 'push-notification-1ecd2',
    storageBucket: 'push-notification-1ecd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARq7Af7aP9FhXson8a2t081fxaxJ96nOA',
    appId: '1:597094987517:ios:ce11ee87f8f2e467d0f094',
    messagingSenderId: '597094987517',
    projectId: 'push-notification-1ecd2',
    storageBucket: 'push-notification-1ecd2.firebasestorage.app',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARq7Af7aP9FhXson8a2t081fxaxJ96nOA',
    appId: '1:597094987517:ios:ce11ee87f8f2e467d0f094',
    messagingSenderId: '597094987517',
    projectId: 'push-notification-1ecd2',
    storageBucket: 'push-notification-1ecd2.firebasestorage.app',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKV3U6NgPSuTCagYbOqqDK1NFkWoDMpjw',
    appId: '1:597094987517:web:e8a509b3258b38ecd0f094',
    messagingSenderId: '597094987517',
    projectId: 'push-notification-1ecd2',
    authDomain: 'push-notification-1ecd2.firebaseapp.com',
    storageBucket: 'push-notification-1ecd2.firebasestorage.app',
    measurementId: 'G-JQG6ETY5LC',
  );
}
